### ISSUE TITLE
Installing the package on macOS

### ISSUE THREAD

**Issue by daffidwilde** [scwatson812/COVID19WastewaterModel#1]
Hi there,

I was hoping to reproduce the work done in the affiliated paper for this repository, and have a look at the code itself. Unfortunately, I don't seem to be able to do that.

My first port of call was to install the package directly from GitHub using `devtools::install_github()`. However, I get an error asking me to check my permissions for the repo. I suspect this is because the package is stored as a ZIP archive on GitHub.

So, to do things manually, I've run the following commands:

```zsh
$ git clone git@github.com:scwatson812/Covid19WastewaterModel.git msr8-lancet
$ cd msr8-lancet
$ unzip Covid19WastewaterModel_0.1.0.zip
$ R CMD INSTALL --build Covid19WastewaterModel
```

After running this set of commands, I can see `Covid19WastewaterModel` package and its documentation appear in the requisite RStudio tabs. I assume that means something has been installed. However, I cannot load or use any of the functions from the package, so something has surely gone awry.

Also, if I move to the install location of the package (`/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Covid19WastewaterSurveillance/`), I am met with the same directory structure as the uncompressed ZIP archive. That is, there are no `.R` files.

The last attempt I made used the following command:

```r
> install.packages(file.choose(), repos=NULL, type="binary")
Enter file name: ~/src/msr8-lancet/CovidWastewaterModel
```

Which led to this error:

```console
tar: Error opening archive: Failed to open '~/src/msr8-lancet/Covid19WastewaterModel'
Error: file ‘~/src/msr8-lancet/Covid19WastewaterModel’ is not a macOS binary package
```

So, I wonder if I'll be able to install this package at all as I'm using macOS.

I would really appreciate a push in the right direction to get this package installed on my machine in such a way that I can go through the code itself.

**Comment by daffidwilde** [comment]
My colleague is also unable to install the package on Windows.

Perhaps an uncompressed version of the code, or installation documentation, could be made available so that the paper can be reproducible?

**Comment by scwatson812** [comment]
Hello,

Sorry to hear you are having trouble with the R package!  To clarify, the package contains the general functions to implement the methods described in the paper.  It does not contain a .R file which performs the exact analysis presented in the paper.  In order to replicate the analysis, you’ll need to use the MC.COVID19.wastewater function and specify the input parameters used in the paper.

The package is relatively small, with only 5 functions.  You can view the code implemented by each function using Covid19WastewaterSurveillance:::function_name_here.  For example Covid19WastewaterSurveillance:::MC.COVID19.wastewater will print the code implemented by the MC.COVID19.wastewater function to the console.

Best,

Stella Self

From: Henry Wilde ***@***.***>
Sent: Thursday, December 16, 2021 7:09 AM
To: scwatson812/COVID19WastewaterModel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [scwatson812/COVID19WastewaterModel] Installing the package (Issue #1)


Hi there,

I was hoping to reproduce the work done in the affiliated paper for this repository, and have a look at the code itself. Unfortunately, I don't seem to be able to do that.

My first port of call was to install the package directly from GitHub using devtools::install_github(). However, I get an error asking me to check my permissions for the repo. I suspect this is because the package is stored as a ZIP archive on GitHub.

So, to do things manually, I've run the following commands:

$ git clone ***@***.******@***.***:scwatson812/Covid19WastewaterModel.git> msr8-lancet

$ cd msr8-lancet

$ unzip Covid19WastewaterModel_0.1.0.zip

$ R CMD INSTALL --build Covid19WastewaterModel

After running this set of commands, I can see Covid19WastewaterModel package and its documentation appear in the requisite RStudio tabs. I assume that means something has been installed.

However, if I move to the install location of the package (/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Covid19WastewaterSurveillance/), I am met with the same directory structure as the uncompressed ZIP archive. That is, there are no .R files.

I would really appreciate a push in the right direction to get this package installed on my machine in such a way that I can go through the code itself.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-fe9b10f7-454455534531-a76d06f6fc619138&q=1&e=10308085-0599-450b-a499-1ea08f173bf9&u=https%3A%2F%2Fgithub.com%2Fscwatson812%2FCOVID19WastewaterModel%2Fissues%2F1>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-fe9b10f7-454455534531-31f96a868a145e93&q=1&e=10308085-0599-450b-a499-1ea08f173bf9&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4ABMVM5XZH24JUKVYYJILURHJFZANCNFSM5KGENLBA>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-fe9b10f7-454455534531-7c3c0f0a9f453c65&q=1&e=10308085-0599-450b-a499-1ea08f173bf9&u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-fe9b10f7-454455534531-14c5614b6d847ff3&q=1&e=10308085-0599-450b-a499-1ea08f173bf9&u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

**Comment by scwatson812** [comment]
Thanks for the message.  I responded to your earlier email prior to seeing this one.  I am running Windows 10 and R 3.6.1.  When I download the zipped package from Github,  am able to successfully install it by clicking on the packages tab in Rstudio, and then clicking install.  In the pop up window, I select the ‘Package Archive File (.zip; .tar.gx)’ option under the ‘Install from:’ dropdown menu.  I then click Browse, and select the download zipped file, and then select Install.

What sort of error are you getting when you attempt the installation?

Best,

Stella

**Comment by daffidwilde** [comment]
Thanks for getting back to me so soon.

I believe `devtools::install_local()` should be able to circumvent the Windows binary issue for me (on macOS). However, I think the R versions are just incompatible. Using `devtools`, I get the following:

```r
> devtools::install_local("~/src/msr8-lancet/Covid19WastewaterSurveillance_0.1.0.zip")
* installing *binary* package ‘Covid19WastewaterSurveillance’ ...
* DONE (Covid19WastewaterSurveillance)
> library(Covid19WastewaterSurveillance)
Error: package or namespace load failed for ‘Covid19WastewaterSurveillance’:
 package ‘Covid19WastewaterSurveillance’ was installed before R 4.0.0: please re-install it
> Covid19WastewaterSurveillance:::MC.COVID19.wastewater
Error: package ‘Covid19WastewaterSurveillance’ was installed before R 4.0.0: please re-install it
```

So, I can install it (allegedly) **but** I can't use it. I assume this is like trying to use a Python 2.x library in Python 3.

My colleague has the same issue on Windows 10. They installed the package through RStudio, but can't use any of the functions within it. They also don't have any `.R` scripts containing the general functions in their install location either.

I'm relatively new to R so maybe that is just how packages are packaged up sometimes! I was expecting it to be like a Python library installation, where a copy of the source code is stored locally under the install location.

**Comment by scwatson812** [comment]
Thanks for the info!  I reached to a colleague to explore this issue further.  We may need to provide an updated version of the package.  In the meantime, I’ve attached an Rscript file which has all the functions defined in the package.  This should have the same functionality as the R package in a less sophisticated format.

Best,

Stella

**Comment by daffidwilde** [comment]
Thank you again, Stella.

Unfortunately, I can't see any attachments here, but I presume that is because I'm responding via GitHub. There wasn't an attachment in the email notification either, though.

In any case, I also contacted the corresponding author about accessing the source code and they've sent me a script containing much of the analysis code I had hoped for.

I'll close this issue now!

All the best,
Henry
